### ISSUE TITLE
添加go命令行工具

### ISSUE THREAD

**Issue by Hans2573** [KpiHang/LeetcodeRecordes#2]
eg，命令行工具叫 lrtools；

demo push 即为自动提交代码（需要命令行输入），功能和目前shell中的auto_功能相似；

Golang 命令行工具自动提交代码（日常刷题、文档笔记、等）
    - 日常刷题：根据文件后缀检测语言；

**Comment by KpiHang** [comment]
fix issue number 搞错了，重新打开；

**Comment by KpiHang** [comment]
方向调整，不确定以后go不go。
