### ISSUE TITLE
借帖求数据处理方式

### ISSUE THREAD

**Issue by Hiilay** [KpiHang/LeetcodeRecordes#3]
大佬你好！冒昧借你这个库进行留言。我想求一下这篇issue下作者提供给你的数据处理流程，十分感谢！https://github.com/YangZhengyi98/DreamRec/issues/3
邮箱：hiilay@163.com

**Comment by KpiHang** [comment]
抱歉，由于当时复现这篇论文的效果并不理想没有接着往下做了，所以代码并未保存。之前邮箱中的附件，我查找后也找不到了，不好意思，建议继续向原作者请求。

**Comment by Hiilay** [comment]
谢谢！还是感谢你！
